---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users":
    get:
      summary: Retrieve users
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: Users retrieved
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                page:
                  type: object
                  properties:
                    size:
                      type: integer
                      example: 10
                    number:
                      type: integer
                      example: 2
    post:
      summary: Create user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: User created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    first_name:
                      type: string
                      example: Vance
                    last_name:
                      type: string
                      example: Bui
                    birthdate:
                      type: integer
                      example: 1681707699
                      description: Epoch timestamp
                    address:
                      type: string
                      example: Paris
                  required:
                  - first_name
                  - last_name
                  - birthdate
                  - address
  "/api/v1/users/{id}":
    get:
      summary: Get info of user based on ID
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: User's info retrieved
        '404':
          description: User's info not found
    patch:
      summary: Update user's info based on ID
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: User's info updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    first_name:
                      type: string
                      example: Vance
                    last_name:
                      type: string
                      example: Bui
                    birthdate:
                      type: integer
                      example: 1681707699
                      description: Epoch timestamp
                    address:
                      type: string
                      example: Paris
    delete:
      summary: Remove user base on ID
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: User removed
servers:
- url: "{defaultHost}"
  variables:
    defaultHost:
      default: https://example.com
components:
  securitySchemes:
    Bearer:
      description: 'Value Format: "Bearer user_access_token"'
      type: apiKey
      name: Authorization
      in: header
